### ISSUE TITLE
Download stops with error

### ISSUE THREAD

**Issue by KruyKaze** [MasterSoft24/CloudCross#1]
Error: "QThread::start: Thread creation error: Resource temporarily unavailable" 
Thanks

**Comment by KruyKaze** [comment]
I stopped it an tried again:

ccross --prefer=remote
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: retry: Resource temporarily unavailable
bash: fork: Resource temporarily unavailable

**Comment by MasterSoft24** [comment]
What is your system and Qt version?

**Comment by KruyKaze** [comment]
Arch 64bit
$ qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib

**Comment by MasterSoft24** [comment]
It seems like  systems total file descriptor limit reached. Try reboot and start again.

**Comment by KruyKaze** [comment]
Rebooted and this it what I get after some files download:

"QThread::start: Thread creation error: Resource temporarily unavailable"

**Comment by MasterSoft24** [comment]
What is  returned if you run

cat /proc/sys/kernel/threads-max

**Comment by KruyKaze** [comment]
62262

**Comment by MasterSoft24** [comment]
I can't reproduce this problem on my computer. Just theoretically this error may happen if app sends to much requests to google drive server.  Can you start programm in Qt Creator in debug  mode and look where this error happen?

**Comment by KruyKaze** [comment]
What is the command? Thanks

**Comment by MasterSoft24** [comment]
qtcreator
Next, "File" > "Create file or project" 

Select "Import project", select "Git clone"

Next, in "Repository" field insert https://github.com/MasterSoft24/CloudCross.git

next, according to the situation

**Comment by KruyKaze** [comment]
I ran it in debug. I don't know how to tell it to run in a certain folder
or how to add the option prefer=remote

I got this:

"Unknown debugger type "No engine"

Unable to create a debugger engine of the type "No engine" "

**Comment by MasterSoft24** [comment]
I think i found problem. Soon i'm fix it and report to you

**Comment by KruyKaze** [comment]
OK thanks

**Comment by MasterSoft24** [comment]
Download executable from http://cloudcross.mastersoft24.ru/ccross and put him into /usr/bin

After that run ccross again

**Comment by KruyKaze** [comment]
I did and tried again. No more errors but it gets stuck after a couple of
hundred files are downloaded and just says "New remote. Downloading." It's
a small file so it shouldn't last that long

**Comment by MasterSoft24** [comment]
Is this error are repeated? With the same file?

**Comment by KruyKaze** [comment]
I tried again and I get this : 
QThread::start: Thread creation error: Resource temporarily unavailable

**Comment by MasterSoft24** [comment]
download http://cloudcross.mastersoft24.ru/ccross again. This version, i think, is ok. Test him and i will update PKGBUILD on AUR

**Comment by KruyKaze** [comment]
This is terrible! It started corrupting files on my google drive:

"/Wallpapers/323 - Zv3KRLd.jpg New remote. Downloading.
/Wallpapers/170 - sxGt57P.jpg Changed local. Uploading.
/Mame/snaps/ncv2.png New remote. Downloading.
/Mame/snaps/dumpmtmt.png Changed local. Uploading.
/Wallpapers/251 - ZcmzJaE.jpg Changed local. Uploading.
^Z
[1]+  Stopped                 ccross --prefer=remote "

**Comment by MasterSoft24** [comment]
yes, that I hurried. I will look deeper.

**Comment by MasterSoft24** [comment]
It's all. I'm fix this bug and update AUR. You can do upgrade. I'm hope now all be ok.
