### ISSUE TITLE
Поддержка прокси

### ISSUE THREAD

**Issue by don-rumata** [MasterSoft24/CloudCross#10]
Доброго времени суток. А можно добавить поддержку переменных `http_proxy`, `https_proxy`, `all_proxy`, ключа `--proxy` и строки в конфиг файле `proxy = `?

**Comment by MasterSoft24** [comment]
Емнип, можно добавить socks5 и http. К следующему релизу добавлю

**Comment by don-rumata** [comment]
Лично для меня критична именно прокся, но если появится поддержка остальных шлюзов - я только "за".

**Comment by MasterSoft24** [comment]
Ты имеешь в виду, использовать системные настройки прокси?

**Comment by don-rumata** [comment]
И их тоже. Я в самом начале написал откуда хотелось бы, чтобы прога брала настройки. Т.е. открываем терминал, пишем `export http_proxy=http://proxy.myhost-with-proxy:port`, запускаем клаудкросс. И она ходит через прокси. Или дописываем строку `proxy = http://proxy.myhost-with-proxy:port` в файл `~/.config/cloudcross/config.conf` и результат тот же самый.

**Comment by MasterSoft24** [comment]
Ага, я понял. Сделаю.

**Comment by don-rumata** [comment]
Каеф.

**Comment by don-rumata** [comment]
[Юху!!!](https://www.linux.org.ru/news/opensource/13022494)
