### ISSUE TITLE
[Feature request] Обработка списка .exclude как .gitignore

### ISSUE THREAD

**Issue by einhander** [MasterSoft24/CloudCross#13]
Добрый день.
Немного не понятна работа файла .exclude. Допустим мне нужно исключить из синхронизации директории и файлы с окончанием .bak. Как это сделать? Или допустим только файлы, а директории синхронизировать?

**Comment by MasterSoft24** [comment]
Типичное применение для файла .exclude это, например при синхронизации домашней директории, исключить из синхронизации папки с музыкой и фильмами

/Music
/Video

А для вашего примера можно попробовать написать небольшой shell-скрипт, который из вывода, например команды find будет динамически формировать файл .include или .exclude и потом запускать ccross

**Comment by einhander** [comment]
Спасибо, я то думал это в какой то мере аналог .gitignore.
Тогда пусть это issue будет фичереквестом, чтобы exclude работало как .gitignore. А пока буду делать скрипт.

**Comment by MasterSoft24** [comment]
Closed by #18
