### ISSUE TITLE
Создание дубликатов директорий в google drive

### ISSUE THREAD

**Issue by einhander** [MasterSoft24/CloudCross#14]
Добрый день.
Я заметил, что иногда cross создает копии директорий которые синхронизирует.
Ключ --no-hidden не помогает запись идет в новую директорию.

**Comment by MasterSoft24** [comment]
Ключ -no-hidden призван управлять синхронизацией фалов и папок с именами начинающимися с точки (linux) или имеющими атрибут hidden (windows).

Аналогичное поведение наблюдал и я. Некоторые папки и файлы оказались задвоены в GoogleDrive. У меня Arch и после нового года прилетело обновление до 5.7 и после этого стали появляться такие артефакты.  Решилось пересборкой. Причина, вероятнее всего, в обновлении Qt.

**Comment by pronin-cc** [comment]
Подобная проблема наблюдалась у меня с официальным клиентом на OSX

**Comment by MasterSoft24** [comment]
Проблема на стороне Google.
