### ISSUE TITLE
Не синхронизуются директории Google Drive, написанные на кириллице

### ISSUE THREAD

**Issue by pronin-cc** [MasterSoft24/CloudCross#15]
Если в корневой директории на Google Drive есть директории, название которых написано на кириллице, то программа их не видит. После переименования латиницей, директории нормально синхронизируются, включая также вложенные директории и файлы с названием на кириллице.

**Comment by MasterSoft24** [comment]
Какая версия Qt у вас? Система? Ставили из исходников или пакетом?

Проверил - работает нормально - вот видео https://youtu.be/61SXt5AwBd0

**Comment by pronin-cc** [comment]
Система -  Ubuntu 17.04
Устанавливал готовый пакет для 16.10

**Comment by MasterSoft24** [comment]
Попробуйте собрать из исходников. Возможно, это что то дистро-специфичное. Я, к сожалению, собрать пакет для 17.04 пока не могу - OBS его еще не предоставляет.
Если в процессе компиляции вылезут ошибки,  пишите - исправим

**Comment by pronin-cc** [comment]
Пересборка ничего нового не дала. Зато выяснилось, что вновь созданные директории видны. А вот со старыми похоже была проблема. Еще выяснилось, что `ccross --list` выводит содержимое не всех директорий.

**Comment by MasterSoft24** [comment]
Ясно, это объясняет #14 и почему это началось - причина все же на стороне гугла. А, что значит выводит список не всех директорий? Что не выводится?

**Comment by pronin-cc** [comment]
К сожалению, никакую зависимость не вижу. Просто пустые директории, переименовывание не помогает

**Comment by MasterSoft24** [comment]
Не понял. Какие директории пустые?

**Comment by pronin-cc** [comment]
Произвольные. Не зависимо от названия и уровня вложенности

**Comment by MasterSoft24** [comment]
Все директории пустые?

**Comment by pronin-cc** [comment]
Только некоторые

**Comment by MasterSoft24** [comment]
А у вас нет возможности проверить это поведение на более старой системе? Что бы уж уточнить - проблема в коде, версии системы или в гугле. 

Если запустить с ключом --force download скачаются все файлы или будут пропуски?

**Comment by pronin-cc** [comment]
`--force download` аналогично не видит эти файлы и деректории.
Проверить на старых системах нет возможности

**Comment by MasterSoft24** [comment]
Когда я столкнулся с #14 у меня не было кириллических имен, просто несколько папок продублировались с теми же именами и заполнились некоторыми файлами из оригинальных папок (не всеми, а хаотично выбранными). Заметив это я начал пробовать вылавливать ошибки, но ничего не найдя прересобрал программу и, попутно, удалил дубли в GD. После этого все заработало, как прежде.

Если файлов не много, то можно скачать их в локальную папку, очистить GD и синхронизировать их либо просто выгрузить.

**Comment by MasterSoft24** [comment]
Проблема та же, что и в #14
