### ISSUE TITLE
Ошибки в инструкциях на сайте

### ISSUE THREAD

**Issue by trufanov-nok** [MasterSoft24/CloudCross#19]
Ну сайте в инструкциях по установке пакетов не отображаются `&&` между командами. Например:
``sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/MasterSoft24/xUbuntu_16.10/ /' > /etc/apt/sources.list.d/cloudcross.list" sudo apt-get update sudo apt-get install cloudcross``

**Comment by MasterSoft24** [comment]
Спасибо, что заметили - уже исправил
