### ISSUE TITLE
Двухуровневая аутентификация google 

### ISSUE THREAD

**Issue by RichardGuarano** [MasterSoft24/CloudCross#21]
Не выходит пройти аутентификацию после того как программа дает ссылку на гугл в гугле жму разрешить мне браузер перенаправление делает на http://127.0.0.1:1973/?state=1&code=4/peVuTwWJdctwj-r-PTAC-m4uElC6udmfy7f7d1LNN4U#
ошибка  и страница не открывается

**Comment by MasterSoft24** [comment]
Это не ошибка, проверьте - в директории, где запускали ccross должен появиться файл .grive

**Comment by RichardGuarano** [comment]
Да файл есть в нем токен

пт, 19 мая 2017 г. в 5:09, Kamensky Vladimir <notifications@github.com>:

**Comment by MasterSoft24** [comment]
Ну вот, значит авторизация прошла успешно и можно начинать работать с облаком.

**Comment by Beanocean** [comment]
I met with a similar problem, after clicking the `Allow` button in authority page, the browser redirected to a new URL (http://127.0.0.1:1973/xxx) which couldn't be reached. And I didn't get `.grive` file in my directory. The feedback in command line was:
![selection_003](https://user-images.githubusercontent.com/5241291/30303350-d5395fa2-97aa-11e7-9c1c-f91ea5f9de0a.png)

**Comment by MasterSoft24** [comment]
You can try build ccross from dev branch. In this version i'm changed redirect to pretty web page. Your feedback message says that request was failed. Cause of this may be on google side. Too little information. Give my more information if you can.

**Comment by Beanocean** [comment]
@MasterSoft24 Hello~ I just paste all the returned error message above. How can I provide more information? Hoping for some instructions.

**Comment by MasterSoft24** [comment]
Qt version, Linux distro, are you build from source code or dowload binary package?

**Comment by Beanocean** [comment]
Qt version is `5.5.1`. Linux distribution is `Ubuntu 16.04.3 LTS (Xenial Xerus)`. 
I have tried to build from source code or install by `apt`.  Both methods were failed in authentication.

**Comment by MasterSoft24** [comment]
I'm can't reproduce this problem.
I'm installed ubuntu 16.04.3 into VM, downloaded  cloudcross_1.4.0-1_amd64.deb from CloudCross home page, installed it and all works fine...

**Comment by Beanocean** [comment]
@MasterSoft24  Could you provide some possible causes of this problem? I want to tackle it, but don't know where to start.

**Comment by MasterSoft24** [comment]
Actually, i don't know what is cause of this problem. Could you make a small screencast and step-by-step reproduce how you gets this error? Maybe this will help..
