### ISSUE TITLE
"Host requires authentication" after force upload for sometime.

### ISSUE THREAD

**Issue by twisp007** [MasterSoft24/CloudCross#24]
I have a large number of files I need to upload to google drive. I use `ccross --force upload`. The files upload fine for some time, then for each file it tries to upload it says `Host requires authentication`.

**Comment by MasterSoft24** [comment]
Hi.
how many files have loaded fine before it started the require  authentication?

**Comment by twisp007** [comment]
I can't say the exact number. But they do keep uploading for a while. Then this authentication error starts. What does the error message mean?

**Comment by MasterSoft24** [comment]
Fixed.
Today (9 sep. 2017) this features placed in dev branch.
