### ISSUE TITLE
the command to auth as gmail gets errors with localhost ip

### ISSUE THREAD

**Issue by Wigberg** [MasterSoft24/CloudCross#26]
Hello, i try now since 3 Weeks to get google drive to run, but everytime i get an error after auth with gmail. 
it connects to localhost and says this website is not reachable.. in terminal i just get these 

Error transferring https://www.googleapis.com/oauth2/v4/*token removed*code=&grant_type=authorization_code&redirect_uri=http://127.0.0.1:1973 - server replied: Bad Request
Authentication failed

so tell me whats the problem and how i get a solution to run this

**Comment by MasterSoft24** [comment]
This is ok. Dont worry. Check your sync folder. If it have a .grive file it means that auth procedure comlete and you can continue work with cloud. In the next release i'm will change this behaviour for remove undefine output at the end of auth.

**Comment by Wigberg** [comment]
ok, you shoulld write it in readme file :D 
but what clouds can i sync with cloudcross too? just dropbox and google? 
and whats the others platformcommands to geht the token? i tryed onedrive and one-drive but it lets appears the google token

**Comment by Wigberg** [comment]
ok nevermind :D i got it
