### ISSUE TITLE
When downloading a file, HTTP error corrupts file.

### ISSUE THREAD

**Issue by bruce-visscher** [MasterSoft24/CloudCross#3]
During file sync, encountered HTTP 401 errors.  When this happened, the local file is populated with the following JSON error message:

```{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}

```

After running ccross again (even with --prefer=remote, new versions of multiple files are created with the above contents.  To recover, the "current" version of the file can be removed.

CloudCross should handle HTTP response codes that indicate failure more intelligently.  E.g., abort with error message, send the reject files to an alternate directory tree, etc.
```

**Comment by MasterSoft24** [comment]
I'm fix it in previous commit
