### ISSUE TITLE
Proposal: safe processing of incompletely downloaded files

### ISSUE THREAD

**Issue by trufanov-nok** [MasterSoft24/CloudCross#35]
After app had crashed (as described in #34 ) I've restarted it with same arguments:
`ccross --provider onedrive --prefer=remote --use-include`
and noticed following output:
```
...
/Image-0098.png New remote. Downloading.
/0074.tif Changed local. Uploading.
    OneDrive does not support zero-length files. Uploading skiped.
...
```
So I killed it. I have to empty folder and redownload all files from scratch as I don't know how many partially downloaded files there and their size.

It's clear that even with `--prefer=remote` the app treats partially downloaded file as locally changed and tries to upload it to the cloud. Hopefully OneDrive not allowed it to upload an empty file.

This means in case of network problem (or laptop power off) some files could be left partially downloaded and ccross will update/damage them in cloud at next synchronization.

Would be better if ccross could download files to some cache folder or create them with ".downloading" extension (for example) and move them to a proper folder or rename to the proper name only after download is completed. In this case it could ignore and delete partially downloaded files after network malfunction.

**Comment by MasterSoft24** [comment]
fixed in dev branch
