### ISSUE TITLE
v1.4.1-rc2 Segfault on auth

### ISSUE THREAD

**Issue by geblanco** [MasterSoft24/CloudCross#43]
Hi!

I might be getting something really wrong, but I cannot get this to work.
With rc1 I can authorize and it works, it generates the .grive file and list the remote files, but the rc2 is not able to authorize, it crashes with this message:
```
ccross -a
-------------------------------------
Please go to this URL and confirm application credentials
https://accounts.google.com/ServiceLogin?passive=1209600&continue=https://accounts.google.com/o/oauth2/v2/auth?...

Token was successfully accepted and saved. To start working with the program run ccross without any options for start full synchronize.
[1]    7722 segmentation fault (core dumped)  ccross -a
```
I tried both having the application previously authorized and from scratch, it crashes the same way.

Also, it crashes when doing a dry-run, both in rc1 and rc2, maybe I could open a new issue for this?

**Comment by MasterSoft24** [comment]
It's a real bug. I'm fixed it. You could see a result in the dev branch. Binary packages will be builded soon. Today you could compile and test from source.
