### ISSUE TITLE
What better way to correct a bi-directional auto sync files?

### ISSUE THREAD

**Issue by bilkoua** [MasterSoft24/CloudCross#47]
What better way to correct a bi-directional auto sync files?

**Comment by MasterSoft24** [comment]
1. If you do not have a synchronized folder yet you need to make it.
1.1 If you want sync local data with cloud

 ` ccross --path /path/to/your/folder --prefer local
`
or

  `ccross --path /path/to/your/folder --force upload`

This action does upload your files to the cloud

1.2 If you want sync remote data with local machine

  `ccross --path /path/to/your/folder --prefer remote`

or

  `ccross --path /path/to/your/folder --force download`

This action does download files from the cloud.

2. For followed synchronize, you can run

   `ccross --path /path/to/your/folder`

In this case, all files which were modified from the last sync will be uploaded or downloaded depending on where is a more newest version of the file.

**Comment by MasterSoft24** [comment]
I hope my answer was useful
