### ISSUE TITLE
failing to upload to gdrive

### ISSUE THREAD

**Issue by Q-Master** [MasterSoft24/CloudCross#48]
downloading works, but if uploading got this:
*** Error in `ccross': double free or corruption (!prev): 0x0000561786ccb620 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x722fb)[0x7f25cff942fb]
/lib/x86_64-linux-gnu/libc.so.6(+0x7895e)[0x7f25cff9a95e]
/lib/x86_64-linux-gnu/libc.so.6(+0x791be)[0x7f25cff9b1be]
/usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4(+0x1eee2)[0x7f25d1820ee2]
/usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4(+0x1fd8f)[0x7f25d1821d8f]
ccross(+0x6d58a)[0x56178624258a]
ccross(+0x6da59)[0x561786242a59]
ccross(+0x60e19)[0x561786235e19]
ccross(+0x60f89)[0x561786235f89]
ccross(+0x2860c)[0x5617861fd60c]
ccross(+0x2afc4)[0x5617861fffc4]
ccross(+0x268fc)[0x5617861fb8fc]
ccross(+0xd940)[0x5617861e2940]
ccross(+0xc3f1)[0x5617861e13f1]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f25cff42561]
ccross(+0xc99a)[0x5617861e199a]
======= Memory map: ========
5617861d5000-561786276000 r-xp 00000000 08:02 14158347                   /usr/local/bin/ccross
561786475000-561786477000 r--p 000a0000 08:02 14158347                   /usr/local/bin/ccross
561786477000-561786478000 rw-p 000a2000 08:02 14158347                   /usr/local/bin/ccross
561786c50000-561787f3c000 rw-p 00000000 00:00 0                          [heap]
7f25c4000000-7f25c4021000 rw-p 00000000 00:00 0 
7f25c4021000-7f25c8000000 ---p 00000000 00:00 0 
7f25c8294000-7f25c8299000 r-xp 00000000 08:02 3670756                    /lib/x86_64-linux-gnu/libnss_dns-2.25.so
7f25c8299000-7f25c8498000 ---p 00005000 08:02 3670756                    /lib/x86_64-linux-gnu/libnss_dns-2.25.so
7f25c8498000-7f25c8499000 r--p 00004000 08:02 3670756                    /lib/x86_64-linux-gnu/libnss_dns-2.25.so
7f25c8499000-7f25c849a000 rw-p 00005000 08:02 3670756                    /lib/x86_64-linux-gnu/libnss_dns-2.25.so
7f25c849a000-7f25c849c000 r-xp 00000000 08:02 3670280                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f25c849c000-7f25c869b000 ---p 00002000 08:02 3670280                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f25c869b000-7f25c869c000 r--p 00001000 08:02 3670280                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f25c869c000-7f25c869d000 rw-p 00002000 08:02 3670280                    /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7f25c869d000-7f25c86a8000 r-xp 00000000 08:02 3670757                    /lib/x86_64-linux-gnu/libnss_files-2.25.so
7f25c86a8000-7f25c88a7000 ---p 0000b000 08:02 3670757                    /lib/x86_64-linux-gnu/libnss_files-2.25.so
7f25c88a7000-7f25c88a8000 r--p 0000a000 08:02 3670757                    /lib/x86_64-linux-gnu/libnss_files-2.25.so
7f25c88a8000-7f25c88a9000 rw-p 0000b000 08:02 3670757                    /lib/x86_64-linux-gnu/libnss_files-2.25.so
7f25c88a9000-7f25c88af000 rw-p 00000000 00:00 0 
7f25c88af000-7f25c88b0000 ---p 00000000 00:00 0 
7f25c88b0000-7f25c90b0000 rw-p 00000000 00:00 0 
7f25c90b0000-7f25c937b000 r--p 00000000 08:02 14031681                   /usr/lib/locale/locale-archive
7f25c937b000-7f25c9382000 r-xp 00000000 08:02 14027812                   /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f25c9382000-7f25c9582000 ---p 00007000 08:02 14027812                   /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f25c9582000-7f25c9583000 r--p 00007000 08:02 14027812                   /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f25c9583000-7f25c9584000 rw-p 00008000 08:02 14027812                   /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f25c9584000-7f25c9598000 r-xp 00000000 08:02 3670072                    /lib/x86_64-linux-gnu/libgpg-error.so.0.22.0
7f25c9598000-7f25c9797000 ---p 00014000 08:02 3670072                    /lib/x86_64-linux-gnu/libgpg-error.so.0.22.0
7f25c9797000-7f25c9798000 r--p 00013000 08:02 3670072                    /lib/x86_64-linux-gnu/libgpg-error.so.0.22.0
7f25c9798000-7f25c9799000 rw-p 00014000 08:02 3670072                    /lib/x86_64-linux-gnu/libgpg-error.so.0.22.0
7f25c9799000-7f25c9809000 r-xp 00000000 08:02 3670067                    /lib/x86_64-linux-gnu/libpcre.so.3.13.3
7f25c9809000-7f25c9a09000 ---p 00070000 08:02 3670067                    /lib/x86_64-linux-gnu/libpcre.so.3.13.3
7f25c9a09000-7f25c9a0a000 r--p 00070000 08:02 3670067                    /lib/x86_64-linux-gnu/libpcre.so.3.13.3
7f25c9a0a000-7f25c9a0b000 rw-p 00071000 08:02 3670067                    /lib/x86_64-linux-gnu/libpcre.so.3.13.3
7f25c9a0b000-7f25cb287000 r-xp 00000000 08:02 14025300                   /usr/lib/x86_64-linux-gnu/libicudata.so.57.1
7f25cb287000-7f25cb486000 ---p 0187c000 08:02 14025300                   /usr/lib/x86_64-linux-gnu/libicudata.so.57.1
7f25cb486000-7f25cb487000 r--p 0187b000 08:02 14025300                   /usr/lib/x86_64-linux-gnu/libicudata.so.57.1
7f25cb487000-7f25cb488000 rw-p 0187c000 08:02 14025300                   /usr/lib/x86_64-linux-gnu/libicudata.so.57.1
7f25cb488000-7f25cb4a2000 r-xp 00000000 08:02 14028536                   /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f25cb4a2000-7f25cb6a1000 ---p 0001a000 08:02 14028536                   /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f25cb6a1000-7f25cb6a2000 r--p 00019000 08:02 14028536                   /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f25cb6a2000-7f25cb6a3000 rw-p 0001a000 08:02 14028536                   /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f25cb6a3000-7f25cb6b6000 r-xp 00000000 08:02 3670765                    /lib/x86_64-linux-gnu/libresolv-2.25.so
7f25cb6b6000-7f25cb8b5000 ---p 00013000 08:02 3670765                    /lib/x86_64-linux-gnu/libresolv-2.25.so
7f25cb8b5000-7f25cb8b6000 r--p 00012000 08:02 3670765                    /lib/x86_64-linux-gnu/libresolv-2.25.so
7f25cb8b6000-7f25cb8b7000 rw-p 00013000 08:02 3670765                    /lib/x86_64-linux-gnu/libresolv-2.25.so
7f25cb8b7000-7f25cb8b9000 rw-p 00000000 00:00 0 
7f25cb8b9000-7f25cb8bc000 r-xp 00000000 08:02 3670094                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f25cb8bc000-7f25cbabb000 ---p 00003000 08:02 3670094                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f25cbabb000-7f25cbabc000 r--p 00002000 08:02 3670094                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f25cbabc000-7f25cbabd000 rw-p 00003000 08:02 3670094                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f25cbabd000-7f25cbac8000 r-xp 00000000 08:02 14031272                   /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f25cbac8000-7f25cbcc7000 ---p 0000b000 08:02 14031272                   /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f25cbcc7000-7f25cbcc8000 r--p 0000a000 08:02 14031272                   /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f25cbcc8000-7f25cbcc9000 rw-p 0000b000 08:02 14031272                   /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f25cbcc9000-7f25cbcda000 r-xp 00000000 08:02 14026589                   /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.4
7f25cbcda000-7f25cbeda000 ---p 00011000 08:02 14026589                   /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.4
7f25cbeda000-7f25cbedb000 r--p 00011000 08:02 14026589                   /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.4
7f25cbedb000-7f25cbedc000 rw-p 00012000 08:02 14026589                   /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.4
7f25cbedc000-7f25cbff6000 r-xp 00000000 08:02 14024750                   /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0
7f25cbff6000-7f25cc1f5000 ---p 0011a000 08:02 14024750                   /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0
7f25cc1f5000-7f25cc200000 r--p 00119000 08:02 14024750                   /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0
7f25cc200000-7f25cc20a000 rw-p 00124000 08:02 14024750                   /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0
7f25cc20a000-7f25cc20b000 rw-p 00000000 00:00 0 
7f25cc20b000-7f25cc31f000 r-xp 00000000 08:02 3670363                    /lib/x86_64-linux-gnu/libgcrypt.so.20.2.1
7f25cc31f000-7f25cc51f000 ---p 00114000 08:02 3670363                    /lib/x86_64-linux-gnu/libgcrypt.so.20.2.1
7f25cc51f000-7f25cc521000 r--p 00114000 08:02 3670363                    /lib/x86_64-linux-gnu/libgcrypt.so.20.2.1
7f25cc521000-7f25cc526000 rw-p 00116000 08:02 3670363                    /lib/x86_64-linux-gnu/libgcrypt.so.20.2.1
7f25cc526000-7f25cc527000 rw-p 00000000 00:00 0 
7f25cc527000-7f25cc5a9000 r-xp 00000000 08:02 14026968                   /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.2
7f25cc5a9000-7f25cc7a9000 ---p 00082000 08:02 14026968                   /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.2
7f25cc7a9000-7f25cc7aa000 r--p 00082000 08:02 14026968                   /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.2
7f25cc7aa000-7f25cc7ab000 rw-p 00083000 08:02 14026968                   /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.2
7f25cc7ab000-7f25cc7df000 r-xp 00000000 08:02 14025458                   /usr/lib/x86_64-linux-gnu/libhogweed.so.4.4
7f25cc7df000-7f25cc9df000 ---p 00034000 08:02 14025458                   /usr/lib/x86_64-linux-gnu/libhogweed.so.4.4
7f25cc9df000-7f25cc9e0000 r--p 00034000 08:02 14025458                   /usr/lib/x86_64-linux-gnu/libhogweed.so.4.4
7f25cc9e0000-7f25cc9e1000 rw-p 00035000 08:02 14025458                   /usr/lib/x86_64-linux-gnu/libhogweed.so.4.4
7f25cc9e1000-7f25ccb5d000 r-xp 00000000 08:02 14028338                   /usr/lib/x86_64-linux-gnu/libunistring.so.2.1.0
7f25ccb5d000-7f25ccd5c000 ---p 0017c000 08:02 14028338                   /usr/lib/x86_64-linux-gnu/libunistring.so.2.1.0
7f25ccd5c000-7f25ccd60000 r--p 0017b000 08:02 14028338                   /usr/lib/x86_64-linux-gnu/libunistring.so.2.1.0
7f25ccd60000-7f25ccd61000 rw-p 0017f000 08:02 14028338                   /usr/lib/x86_64-linux-gnu/libunistring.so.2.1.0
7f25ccd61000-7f25ccd62000 rw-p 00000000 00:00 0 
7f25ccd62000-7f25cce73000 r-xp 00000000 08:02 3670229                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.5400.2
7f25cce73000-7f25cd073000 ---p 00111000 08:02 3670229                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.5400.2
7f25cd073000-7f25cd074000 r--p 00111000 08:02 3670229                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.5400.2
7f25cd074000-7f25cd075000 rw-p 00112000 08:02 3670229                    /lib/x86_64-linux-gnu/libglib-2.0.so.0.5400.2
7f25cd075000-7f25cd076000 rw-p 00000000 00:00 0 
7f25cd076000-7f25cd079000 r-xp 00000000 08:02 3670730                    /lib/x86_64-linux-gnu/libdl-2.25.so
7f25cd079000-7f25cd278000 ---p 00003000 08:02 3670730                    /lib/x86_64-linux-gnu/libdl-2.25.so
7f25cd278000-7f25cd279000 r--p 00002000 08:02 3670730                    /lib/x86_64-linux-gnu/libdl-2.25.so
7f25cd279000-7f25cd27a000 rw-p 00003000 08:02 3670730                    /lib/x86_64-linux-gnu/libdl-2.25.so
7f25cd27a000-7f25cd28a000 r-xp 00000000 08:02 14026103                   /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1.0
7f25cd28a000-7f25cd489000 ---p 00010000 08:02 14026103                   /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1.0
7f25cd489000-7f25cd48a000 r--p 0000f000 08:02 14026103                   /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1.0
7f25cd48a000-7f25cd48b000 rw-p 00010000 08:02 14026103                   /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1.0
7f25cd48b000-7f25cd4f7000 r-xp 00000000 08:02 14034065                   /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0.4.0
7f25cd4f7000-7f25cd6f6000 ---p 0006c000 08:02 14034065                   /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0.4.0
7f25cd6f6000-7f25cd6f7000 r--p 0006b000 08:02 14034065                   /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0.4.0
7f25cd6f7000-7f25cd6f8000 rw-p 0006c000 08:02 14034065                   /usr/lib/x86_64-linux-gnu/libpcre2-16.so.0.4.0
7f25cd6f8000-7f25cd888000 r-xp 00000000 08:02 14028453                   /usr/lib/x86_64-linux-gnu/libicuuc.so.57.1
7f25cd888000-7f25cda88000 ---p 00190000 08:02 14028453                   /usr/lib/x86_64-linux-gnu/libicuuc.so.57.1
7f25cda88000-7f25cda9a000 r--p 00190000 08:02 14028453                   /usr/lib/x86_64-linux-gnu/libicuuc.so.57.1
7f25cda9a000-7f25cda9b000 rw-p 001a2000 08:02 14028453                   /usr/lib/x86_64-linux-gnu/libicuuc.so.57.1
7f25cda9b000-7f25cda9d000 rw-p 00000000 00:00 0 
7f25cda9d000-7f25cdd01000 r-xp 00000000 08:02 14025750                   /usr/lib/x86_64-linux-gnu/libicui18n.so.57.1
7f25cdd01000-7f25cdf01000 ---p 00264000 08:02 14025750                   /usr/lib/x86_64-linux-gnu/libicui18n.so.57.1
7f25cdf01000-7f25cdf0e000 r--p 00264000 08:02 14025750                   /usr/lib/x86_64-linux-gnu/libicui18n.so.57.1
7f25cdf0e000-7f25cdf10000 rw-p 00271000 08:02 14025750                   /usr/lib/x86_64-linux-gnu/libicui18n.so.57.1
7f25cdf10000-7f25cdf11000 rw-p 00000000 00:00 0 
7f25cdf11000-7f25cdf2a000 r-xp 00000000 08:02 3670250                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f25cdf2a000-7f25ce129000 ---p 00019000 08:02 3670250                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f25ce129000-7f25ce12a000 r--p 00018000 08:02 3670250                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f25ce12a000-7f25ce12b000 rw-p 00019000 08:02 3670250                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7f25ce12b000-7f25ce139000 r-xp 00000000 08:02 14025322                   /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.8
7f25ce139000-7f25ce338000 ---p 0000e000 08:02 14025322                   /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.8
7f25ce338000-7f25ce339000 r--p 0000d000 08:02 14025322                   /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.8
7f25ce339000-7f25ce33a000 rw-p 0000e000 08:02 14025322                   /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.8
7f25ce33a000-7f25ce387000 r-xp 00000000 08:02 14025323                   /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.8
7f25ce387000-7f25ce587000 ---p 0004d000 08:02 14025323                   /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.8
7f25ce587000-7f25ce589000 r--p 0004d000 08:02 14025323                   /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.8
7f25ce589000-7f25ce58a000 rw-p 0004f000 08:02 14025323                   /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.8
7f25ce58a000-7f25ce58c000 rw-p 00000000 00:00 0 
7f25ce58c000-7f25ce58f000 r-xp 00000000 08:02 3670073                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f25ce58f000-7f25ce78e000 ---p 00003000 08:02 3670073                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f25ce78e000-7f25ce78f000 r--p 00002000 08:02 3670073                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f25ce78f000-7f25ce790000 rw-p 00003000 08:02 3670073                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f25ce790000-7f25ce7bf000 r-xp 00000000 08:02 14026409                   /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f25ce7bf000-7f25ce9be000 ---p 0002f000 08:02 14026409                   /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f25ce9be000-7f25ce9c0000 r--p 0002e000 08:02 14026409                   /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f25ce9c0000-7f25ce9c1000 rw-p 00030000 08:02 14026409                   /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f25ce9c1000-7f25ce9c2000 rw-p 00000000 00:00 0 
7f25ce9c2000-7f25cea8a000 r-xp 00000000 08:02 14026987                   /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f25cea8a000-7f25cec89000 ---p 000c8000 08:02 14026987                   /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f25cec89000-7f25cec97000 r--p 000c7000 08:02 14026987                   /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f25cec97000-7f25cec9a000 rw-p 000d5000 08:02 14026987                   /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f25cec9a000-7f25cece2000 r-xp 00000000 08:02 14026429                   /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f25cece2000-7f25ceee1000 ---p 00048000 08:02 14026429                   /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f25ceee1000-7f25ceee3000 r--p 00047000 08:02 14026429                   /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f25ceee3000-7f25ceee5000 rw-p 00049000 08:02 14026429                   /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f25ceee5000-7f25cf041000 r-xp 00000000 08:02 14029435                   /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.8
7f25cf041000-7f25cf241000 ---p 0015c000 08:02 14029435                   /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.8
7f25cf241000-7f25cf24e000 r--p 0015c000 08:02 14029435                   /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.8
7f25cf24e000-7f25cf24f000 rw-p 00169000 08:02 14029435                   /usr/lib/x86_64-linux-gnu/libgnutls.so.30.14.8
7f25cf24f000-7f25cf250000 rw-p 00000000 00:00 0 
7f25cf250000-7f25cf285000 r-xp 00000000 08:02 14033330                   /usr/lib/x86_64-linux-gnu/libnettle.so.6.4
7f25cf285000-7f25cf484000 ---p 00035000 08:02 14033330                   /usr/lib/x86_64-linux-gnu/libnettle.so.6.4
7f25cf484000-7f25cf486000 r--p 00034000 08:02 14033330                   /usr/lib/x86_64-linux-gnu/libnettle.so.6.4
7f25cf486000-7f25cf487000 rw-p 00036000 08:02 14033330                   /usr/lib/x86_64-linux-gnu/libnettle.so.6.4
7f25cf487000-7f25cf494000 r-xp 00000000 08:02 14026114                   /usr/lib/x86_64-linux-gnu/libpsl.so.5.2.0
7f25cf494000-7f25cf693000 ---p 0000d000 08:02 14026114                   /usr/lib/x86_64-linux-gnu/libpsl.so.5.2.0
7f25cf693000-7f25cf694000 r--p 0000c000 08:02 14026114                   /usr/lib/x86_64-linux-gnu/libpsl.so.5.2.0
7f25cf694000-7f25cf695000 rw-p 0000d000 08:02 14026114                   /usr/lib/x86_64-linux-gnu/libpsl.so.5.2.0
7f25cf695000-7f25cf6c0000 r-xp 00000000 08:02 14030964                   /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
7f25cf6c0000-7f25cf8c0000 ---p 0002b000 08:02 14030964                   /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
7f25cf8c0000-7f25cf8c1000 r--p 0002b000 08:02 14030964                   /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
7f25cf8c1000-7f25cf8c2000 rw-p 0002c000 08:02 14030964                   /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
7f25cf8c2000-7f25cf8dd000 r-xp 00000000 08:02 14027315                   /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f25cf8dd000-7f25cfadd000 ---p 0001b000 08:02 14027315                   /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f25cfadd000-7f25cfade000 r--p 0001b000 08:02 14027315                   /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f25cfade000-7f25cfadf000 rw-p 0001c000 08:02 14027315                   /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f25cfadf000-7f25cfafb000 r-xp 00000000 08:02 14026519                   /usr/lib/x86_64-linux-gnu/libidn2.so.0.3.3
7f25cfafb000-7f25cfcfa000 ---p 0001c000 08:02 14026519                   /usr/lib/x86_64-linux-gnu/libidn2.so.0.3.3
7f25cfcfa000-7f25cfcfb000 r--p 0001b000 08:02 14026519                   /usr/lib/x86_64-linux-gnu/libidn2.so.0.3.3
7f25cfcfb000-7f25cfcfc000 rw-p 0001c000 08:02 14026519                   /usr/lib/x86_64-linux-gnu/libidn2.so.0.3.3
7f25cfcfc000-7f25cfd1f000 r-xp 00000000 08:02 14035503                   /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.15.1
7f25cfd1f000-7f25cff1e000 ---p 00023000 08:02 14035503                   /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.15.1
7f25cff1e000-7f25cff1f000 r--p 00022000 08:02 14035503                   /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.15.1
7f25cff1f000-7f25cff22000 rw-p 00023000 08:02 14035503                   /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.15.1
7f25cff22000-7f25d00bb000 r-xp 00000000 08:02 3670700                    /lib/x86_64-linux-gnu/libc-2.25.so
7f25d00bb000-7f25d02bb000 ---p 00199000 08:02 3670700                    /lib/x86_64-linux-gnu/libc-2.25.so
7f25d02bb000-7f25d02bf000 r--p 00199000 08:02 3670700                    /lib/x86_64-linux-gnu/libc-2.25.so
7f25d02bf000-7f25d02c1000 rw-p 0019d000 08:02 3670700                    /lib/x86_64-linux-gnu/libc-2.25.so
7f25d02c1000-7f25d02c5000 rw-p 00000000 00:00 0 
7f25d02c5000-7f25d02db000 r-xp 00000000 08:02 3670096                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f25d02db000-7f25d04da000 ---p 00016000 08:02 3670096                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f25d04da000-7f25d04db000 r--p 00015000 08:02 3670096                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f25d04db000-7f25d04dc000 rw-p 00016000 08:02 3670096                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f25d04dc000-7f25d05ee000 r-xp 00000000 08:02 3670736                    /lib/x86_64-linux-gnu/libm-2.25.so
7f25d05ee000-7f25d07ed000 ---p 00112000 08:02 3670736                    /lib/x86_64-linux-gnu/libm-2.25.so
7f25d07ed000-7f25d07ee000 r--p 00111000 08:02 3670736                    /lib/x86_64-linux-gnu/libm-2.25.so
7f25d07ee000-7f25d07ef000 rw-p 00112000 08:02 3670736                    /lib/x86_64-linux-gnu/libm-2.25.so
7f25d07ef000-7f25d095f000 r-xp 00000000 08:02 14027063                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f25d095f000-7f25d0b5f000 ---p 00170000 08:02 14027063                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f25d0b5f000-7f25d0b69000 r--p 00170000 08:02 14027063                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f25d0b69000-7f25d0b6b000 rw-p 0017a000 08:02 14027063                   /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f25d0b6b000-7f25d0b6e000 rw-p 00000000 00:00 0 
7f25d0b6e000-7f25d0b87000 r-xp 00000000 08:02 3670764                    /lib/x86_64-linux-gnu/libpthread-2.25.so
7f25d0b87000-7f25d0d86000 ---p 00019000 08:02 3670764                    /lib/x86_64-linux-gnu/libpthread-2.25.so
7f25d0d86000-7f25d0d87000 r--p 00018000 08:02 3670764                    /lib/x86_64-linux-gnu/libpthread-2.25.so
7f25d0d87000-7f25d0d88000 rw-p 00019000 08:02 3670764                    /lib/x86_64-linux-gnu/libpthread-2.25.so
7f25d0d88000-7f25d0d8c000 rw-p 00000000 00:00 0 
7f25d0d8c000-7f25d1266000 r-xp 00000000 08:02 14039821                   /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.2
7f25d1266000-7f25d1465000 ---p 004da000 08:02 14039821                   /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.2
7f25d1465000-7f25d1471000 r--p 004d9000 08:02 14039821                   /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.2
7f25d1471000-7f25d1472000 rw-p 004e5000 08:02 14039821                   /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.9.2
7f25d1472000-7f25d1476000 rw-p 00000000 00:00 0 
7f25d1476000-7f25d15f9000 r-xp 00000000 08:02 14030824                   /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.9.2
7f25d15f9000-7f25d17f9000 ---p 00183000 08:02 14030824                   /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.9.2
7f25d17f9000-7f25d17ff000 r--p 00183000 08:02 14030824                   /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.9.2
7f25d17ff000-7f25d1801000 rw-p 00189000 08:02 14030824                   /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.9.2
7f25d1801000-7f25d1802000 rw-p 00000000 00:00 0 
7f25d1802000-7f25d1882000 r-xp 00000000 08:02 14038464                   /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.5.0
7f25d1882000-7f25d1a81000 ---p 00080000 08:02 14038464                   /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.5.0
7f25d1a81000-7f25d1a85000 r--p 0007f000 08:02 14038464                   /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.5.0
7f25d1a85000-7f25d1a86000 rw-p 00083000 08:02 14038464                   /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.5.0
7f25d1a86000-7f25d1aa9000 r-xp 00000000 08:02 3670163                    /lib/x86_64-linux-gnu/ld-2.25.so
7f25d1c3c000-7f25d1c52000 rw-p 00000000 00:00 0 
7f25d1c7c000-7f25d1c7d000 rw-p 00000000 00:00 0 
7f25d1c7d000-7f25d1ca7000 r--s 00000000 08:02 14287358                   /usr/share/mime/mime.cache
7f25d1ca7000-7f25d1ca8000 r--s 00000000 08:02 12329317                   /home/qmaster/.local/share/mime/mime.cache
7f25d1ca8000-7f25d1ca9000 r--p 00022000 08:02 3670163                    /lib/x86_64-linux-gnu/ld-2.25.so
7f25d1ca9000-7f25d1caa000 rw-p 00023000 08:02 3670163                    /lib/x86_64-linux-gnu/ld-2.25.so
7f25d1caa000-7f25d1cab000 rw-p 00000000 00:00 0 
7ffe7ceac000-7ffe7cecd000 rw-p 00000000 00:00 0                          [stack]
7ffe7cf30000-7ffe7cf33000 r--p 00000000 00:00 0                          [vvar]
7ffe7cf33000-7ffe7cf35000 r-xp 00000000 00:00 0                          [vdso]

**Comment by MasterSoft24** [comment]
Need more information
1. Linux distro
2. Qt version
3. CloudCross version
3. Installation method (from source or binary package)
4. Which provider generates this error.
5. Parameters which you used for ccross starting

**Comment by MasterSoft24** [comment]
Closing cause (Need more information)
