### ISSUE TITLE
Not able install base-devel qt5-base in Arch

### ISSUE THREAD

**Issue by SamuelMiller** [MasterSoft24/CloudCross#5]
I am unable to install base-devel qt5-base, as per your instructions, in Arch (64 bit Manjaro XFCE 16.06) with out getting the following error.

Almost all of base-devel qt5-base is already preinstalled. However I get this conflict:

looking for conflicting packages...
:: gcc and gcc-multilib are in conflict. Remove gcc-multilib? [y/N] N
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: gcc and gcc-multilib are in conflict

Isn't gcc-multilib  required for 64bit? Thaniks, Sam

**Comment by MasterSoft24** [comment]
No, gcc-multilib required for building 32 bit application on 64 bit system and gcc-multilib replaces/provides gcc. 
As described in Arch wiki you can do

```
# pacman -S gcc-multilib
resolving dependencies...
warning: dependency cycle detected:
warning: lib32-gcc-libs will be installed before its gcc-libs-multilib dependency
looking for inter-conflicts...
:: gcc-libs-multilib and gcc-libs are in conflict. Remove gcc-libs? [y/N] y
:: binutils-multilib and binutils are in conflict. Remove binutils? [y/N] y
:: gcc-multilib and gcc are in conflict. Remove gcc? [y/N] y
:: libtool-multilib and libtool are in conflict. Remove libtool? [y/N] y

Remove (4): gcc-libs-4.6.1-1  binutils-2.21.1-1  gcc-4.6.1-1  libtool-2.4-4

Total Removed Size:   87.65 MB

Targets (7): lib32-glibc-2.14-4  lib32-gcc-libs-4.6.1-1  gcc-libs-multilib-4.6.1-1  binutils-multilib-2.21.1-1
             gcc-multilib-4.6.1-1  lib32-libtool-2.4-2  libtool-multilib-2.4-2

Total Download Size:    25.04 MB
Total Installed Size:   108.27 MB

Proceed with installation? [Y/n]
```

**Comment by SamuelMiller** [comment]
Thanks for your advice. Manjaro actually has base-devel qt5-base preinstalled except with gcc-multilib instead of gcc. All I had to do was compile CloudCross.
