### ISSUE TITLE
CloudCross is command line tool?

### ISSUE THREAD

**Issue by mrakus1** [MasterSoft24/CloudCross#53]
Hello.

Is CloudCross command line tool or not?
I tried to use deb based version and face with issue that deb package want to use qtbase5-dev & etc packages. I suppose it is no necessity for work. I suppose this is issue

Please fix this. Thank you

**Comment by MasterSoft24** [comment]
You right! Fixed. 
`Depends: libqt5network5, qtbase5, qt5-qmake, libcurl4-openssl`
