### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by gvintux** [MasterSoft24/CloudCross#54]
$ sudo make uninstall
...
rm -f /usr/bin/ccross
**rmdir /usr/bin/** **it's not funny**
rmdir: failed to remove '/usr/bin/': Directory not empty
Makefile:3675: recipe for target 'uninstall_target' failed
...

**Comment by MasterSoft24** [comment]
fixed

**Comment by programmador** [comment]
Seems like there are some troubles now. I'm trying to build 1.4.2 for Gentoo and it prints errors:
```
WARNING: cccurl.path is not defined: install target not created
WARNING: ccross.path is not defined: install target not created
```
As a result there are no files installed with the package.

I've tried building in a separate directory without gentoo/portage just using qmake & make as it's suggested in README. It prints same errors but the files are actually being built (while building with portage I didn't see any compile process at all though it works fine for previous cloudcross versions).

I'm just briefly familiar with Qt and it's build systems. The docs http://doc.qt.io/qt-5/qmake-variable-reference.html say that the way it was done before fix is actually usual for Qt:
```
target.path += $$[QT_INSTALL_PLUGINS]/imageformats
INSTALLS += target
```
There is only a brief mention about `.target` SUBDIR  behaviour modifier without any examples so I couldn't determine what's the correct way to fix the issue.

My brain tells that there's nothing wrong with .pro files currently and I just have to change somehow behaiviour of my gentoo ebuild to match building process with the one mentioned in README (separate build subdirectory) - is it correct?

**Comment by programmador** [comment]
I didn't call "make" though it wasn't needed for previous versions. Now I do and the result is:
make: *** No rule to make target 'install'.  Stop.

Quite predictable. I'll put bin files to /usr/bin directly in gentoo ebuild (package) code instead of calling make install. So it's overridable issue. But maybe it should be considered as a bug.

BTW for previous versions (when I called just `qmake ***.pro` without calling `make` before `make install`) it seems like only ccross binary was built and installed, without ccross-curl.

**Comment by MasterSoft24** [comment]
> seems like only ccross binary was built and installed, without ccross-curl.

Yes. Previous versions has only ccross binary file. 

Could you paste  qmake outputs? 

Genarally, build process seems like this 

```
cd CloudCrooss-master

mkdir build

cd build

qmake ..

make

make install
```

**Comment by programmador** [comment]
[Makefile.txt](https://github.com/MasterSoft24/CloudCross/files/2201577/Makefile.txt)
Here is qmake output

**Comment by programmador** [comment]
And make output
[stderr.log](https://github.com/MasterSoft24/CloudCross/files/2201586/stderr.log)
[stdout.log](https://github.com/MasterSoft24/CloudCross/files/2201588/stdout.log)

**Comment by programmador** [comment]
make stdout and stderr combined:
[out-and-err.log](https://github.com/MasterSoft24/CloudCross/files/2201598/out-and-err.log)

**Comment by programmador** [comment]
1.4.2 is ready for Gentoo:
https://bitbucket.org/programmador/gentoo-overlay/src/default/net-misc/cloudcross/cloudcross-1.4.2.ebuild
As You can see there's no `make install` call in `src_install()` - now I'm just manually inserting binaries

**Comment by MasterSoft24** [comment]
So, possibly it is the right way but I do check install target
