### ISSUE TITLE
проблема с документами из Gdrive

### ISSUE THREAD

**Issue by fres-a** [MasterSoft24/CloudCross#57]
mint 18.3
qt 5.6.1
ext4
CloudCross v1.4.1(собран из исходников)
при нормальной снхронизации (ccross -p /home/user/Gdrive --prefer=remote) не скачиваются документы созданные через Google Docs, если указать --convert-doc то содержимое всех документов становится таким 
![image](https://user-images.githubusercontent.com/37847673/38041922-adec58b2-32bb-11e8-9259-d818b396fcb2.png)

**Comment by MasterSoft24** [comment]
Подтверждено. В ближайшее время проверю, что поменялось

**Comment by MasterSoft24** [comment]
Исправлено. Были какие то изменения в api
