### ISSUE TITLE
проблема с синхронизацией

### ISSUE THREAD

**Issue by fres-a** [MasterSoft24/CloudCross#59]
при первой синхронизации падают такие ошибки:
"Failure when receiving data from the peerSSL read: error:00000000:lib(0):func(0):reason(0), errno 104"
"SSL connect errorUnknown SSL protocol error in connection to www.googleapis.com:443 "
если запустить ещё раз то он просто удаляет всё из папки для синхронизации.

**Comment by fres-a** [comment]
странно, сутки падали ошибки, а теперь отпустило

**Comment by fres-a** [comment]
снова эти ошибки, но теперь хоть синхронизирует

**Comment by MasterSoft24** [comment]
может РКН что то мутит опять?

**Comment by fres-a** [comment]
да, дело в ркн, через впн проблем нет
