### ISSUE TITLE
Error getting cloud information.

### ISSUE THREAD

**Issue by roachsinai** [MasterSoft24/CloudCross#61]
I want to use `ccross --provider dropbox --cloud-space` to get `cloud space` but I get an Error.

```
➜  Dropbox ccross --provider dropbox
➜  Dropbox ccross --provider dropbox --cloud-space
Error getting cloud information 
```

What's the correct method?

**Comment by MasterSoft24** [comment]
I'd confirm it. It's a bug. Maybe dropbox API methods have been changed. In the next release, I fix it.

**Comment by roachsinai** [comment]
Thanks！

**Comment by MasterSoft24** [comment]
Approx September , 27 will be released new version whose fixed this bug
