### ISSUE TITLE
Is there a config file for synchronize directory and authentication code?

### ISSUE THREAD

**Issue by roachsinai** [MasterSoft24/CloudCross#64]
Hi, I didn't find a config file like `~/.config/ccross`. So, if I changed cloud platform, how to remove the old authentication information？

**Comment by MasterSoft24** [comment]
You can just remove .dbox file (for dropbox) or  similar files related for other providers. Global config file doesn't implemented yet

**Comment by roachsinai** [comment]
@MasterSoft24 Thanks a lot!
