### ISSUE TITLE
Debian package has nonexisting dependencies

### ISSUE THREAD

**Issue by mrfrenzy** [MasterSoft24/CloudCross#65]
Hi

I am trying to install cloudcross on either debian 8 or 9 using your repository from:
https://software.opensuse.org//download.html?project=home%3AMasterSoft24&package=cloudcross

Whenever I try to install I get errors due to missing dependencies:
qtbase5 and libcurl4-openssl.

Packages with these exact names do not exist in Debian versions 8 or 9 repositories.

**Comment by MasterSoft24** [comment]
I'm fix dependencies and rebuild packages, please try reinstall package and write result of this.

**Comment by korakios** [comment]
Downloaded the deb package but still have the same problem
`cloudcross : Depends: libcurl4 but it is not installable`
But I already have
`libcurl4-openssl-dev` installed (v.7.52.1-5+deb9u6)
I am on debian ~~jessie~~ stretch based system

**Comment by MasterSoft24** [comment]
`libcurl4-openssl-dev` is a development package. I'm don't have a Debian based OS but quick search got a https://packages.debian.org/search?suite=default&section=all&arch=any&lang=en&searchon=names&keywords=libcurl4

I'm know about this problem but don't know how fix it for all debian-based systems at all. Any ideas about this will be suitable

**Comment by korakios** [comment]
Well , now it’s obvious, it’s not (libcurl4) in the stable release !
Will post back when it lands to ‘Stretch’ , thank you for your time :)

**Comment by dmak** [comment]
Debian Buster provides `libcurl4` but CloudCross does not run on it, see issue #72. Apparently I think that CloudCross should have dependency `libcurl3 | libcurl4` (either of two) and be linked against `libcurl.so.4`.
