### ISSUE TITLE
Sync with OneDrive always removes new remote files (--merge option request)

### ISSUE THREAD

**Issue by MAnantharaman** [MasterSoft24/CloudCross#68]
I really like CloudCross but after using for some time I found it was always deleting new pictures my old Nokia Lumia was uploading to OneDrive, so I checked the code and think we need the attached patch to prevent this.

Regards, Martin
[msonedrive.cpp.patch.txt](https://github.com/MasterSoft24/CloudCross/files/2486306/msonedrive.cpp.patch.txt)

**Comment by MasterSoft24** [comment]
Would you show me your parameters when your photos was deleted during sync?

**Comment by MAnantharaman** [comment]
Sure, it was just ...
ccross --provider onedrive
... in the directory where I sync OneDrive (~/OneDrive). As far as I understand --prefer local is default and the code-block I identified uses that EVEN if the remote file is newer. The output of ccross then was "Local deleted, deleting remote" or so.

**Comment by MasterSoft24** [comment]
If you use --prefer local (by default) ccross will make a full copy of your directory into the cloud and will remove all files which not exists in the local folder. For avoid of this, you can use an .exclude file with names of your existing remote files or make sync into a dedicated folder in the cloud.

For example:
Let you have a folder which you want to sync named `~/OneDrive/Sync` then you can do

```
echo "/Sync" > ~/OneDrive/.include
cd ~/OneDrive
ccross --provider onedrive
```
Little bit more information you can see on https://cloudcross.mastersoft24.ru/blog/2017/09/cloudcross-141-new-features-of-include-and-exclude-file-lists

An `.include` and `.exclude` files is a powerful tool for more flexible control of the sync process

**Comment by MAnantharaman** [comment]
I am aware of these techniques and use them:-) Nevertheless, I feel that a "sync" (inherently two-way) should merge new files from both sides, with --prefer governing conflict-resolution - otherwise it is really a one-way "mirror" operation. And as far as I can see the whole point in maintaining state is to be able to detect newer files - except that without my proposed patch they get deleted unconditionally on remote side. An alternative might be to have an option (--merge?) which then activates a two-way sync.

**Comment by MasterSoft24** [comment]
You can try a --force upload at first time and regular sync afterwards. That about --merge option, I think this is a great idea and possibly I'm realize it in the next release

**Comment by MAnantharaman** [comment]
Hi Vladimir,

that would be great - but since I had a bit of time on hand and like to brush up my programming-abilities (coming from the 1980s) oft and on I analyzed my use-cases (with some look-across to tools like rsync, rclone) further and hacked up a prototype for OneDrive **only** (though with some small changes to the global framework).

Briefly:

- Extended SyncStrategy to several more options: MergeLocal, MergeRemote,  UpdateLocal,  UpdateRemote, MirrorLocal, MirrorRemote.
- Concentrated sync-logic in filelist_defineObjectState (now called from createSyncFileList only), simplifying doSync and checkFolderStructures in the process.
- Used Qt logging-framework to be able to debug.
- Added a couple of options for the new strategies, for suppressing checksums (accelerates reading local files) and verbose output.

Now, it is doing more or less what I want it to (for OneDrive!) and I am attaching a patch as-is which you may or may not use (if you do, then an acknowledgement would be nice).
[CloudCross-master.patch.txt](https://github.com/MasterSoft24/CloudCross/files/2514298/CloudCross-master.patch.txt)

On the other hand, I found a deeper-lying problem that is too big for me: I noticed that while the sync-algorithm now works as I expect, far more changes were being detected than I expected - _when also using the modification-time for comparison_. A deeper analysis of the OneDrive API showed that the lastModifiedDateTime attribute is really not what one naively expects: It tracks ANY change to the object (including metadata) and does not correlate well with creation/modification-time of the local object. For that the API seems to provide teh fileSystemInfo attribute which contains the creation/modification-time of the local object. I strongly feel that this information neerds to be used (when readingf data and comparing remote/local) - but also when inserting/updating a remote item. And that is beyond what I am able/willing to do:-(

BTW: I also found that allowing multi-threaded sync not only gave me garbled output - but also some strange errors deep out of Qt ...

Regards, Martin
