### ISSUE TITLE
Mail.Ru authentication issue

### ISSUE THREAD

**Issue by alexks02** [MasterSoft24/CloudCross#71]
Hi there,

xander@hp250:/media/xander/My Book/Cloud$ ccross -a --provider mailru --login "my_login@mail.ru" --password "my_password"
Authentication failed

Password is correct, it's for sure. I tried do not use quotes as well, result is the same. How can I debug it?

Thanks, Alexander

**Comment by MasterSoft24** [comment]
Hi. It's seems like mail.ru makes some changes. In the near future i'm fix it.

**Comment by MasterSoft24** [comment]
Look at v1.4.5. In this version I'm have fixed an auth error for mail.ru

**Comment by alexks02** [comment]
Thanks! Will check it today and reply if encounter any issues

**Comment by dmak** [comment]
I have the same problem with v1.4.5. User/password are correct but authentication fails. I suspect that is the same problem as in [rclone #3637](https://github.com/rclone/rclone/issues/3637#issuecomment-546419084), namely, additional step should be performed if 2FA authentication is enabled for MailRu (my case).

**Comment by MasterSoft24** [comment]
Yes, you are right. 2FA authentication isn't supported. And in addition, mail.ru  breaks authentication compatible again. I think I've to remove mail.ru support until they do not publish official API
