### ISSUE TITLE
Cannot run ccoss on Debian Buster due to missing CURL_OPENSSL_3 symbol

### ISSUE THREAD

**Issue by dmak** [MasterSoft24/CloudCross#72]
After installing `cloudcross_1.4.5-1_i386.deb` on Debian Buster and running `ccross` I get the following problem:
```
$ ccross
ccross: /usr/lib/i386-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ccross)
```
I think that `ccross` was not compiled against latest `libcurl4`.
* Could you please check that you have the latest [`libcurl4-openssl-dev`](https://packages.debian.org/buster/libcurl4-openssl-dev) package installed on your build system?
* Could you please check that the symbol `CURL_OPENSSL_3` is actually present in `libcurl.so.4` on your build system?

Additional information:
* [Curl team](https://github.com/curl/curl/issues/2433#issuecomment-377046239) says that symbol was added by Debian to the package (hence not part of original sources). Looks like this symbol was removed in `libcurl4` (it exists in `libcurl3`).
* `libcurl4` and `libcurl3` cannot co-exist on the same system, as they both provide `libcurl.so.4` but there is ABI change.

**Comment by MasterSoft24** [comment]
My build system (build.opensuse.org) does not have a Debian Buster among proposed disk images. And libcurl have a version current for Stretch release. You can try to build the cloudcross from source code anytime.  Of course, I'll try to fix it but as I remember last time these fixes broke builds for other Debian-based distros.

**Comment by dmak** [comment]
From my point of view there is something wrong with artifact `cloudcross_1.4.5-1_i386.deb` because it cannot be installed on Debian Stretch (see issue #65 and also [libcurl4 search on Debian repo](https://packages.debian.org/search?suite=all&searchon=names&keywords=libcurl4)), and when installed Buster, it does not work. Quickfix would be to replace `libcurl4` with `libcurl3`, but sooner or later `libcurl3` becomes deprecated.

I've noticed that `control` file in `cloudcross_1.4.5-1_i386.deb` reads:
```
Depends: libqt5network5, qt5-default, qt5-qmake, libcurl4
```
while [`debian.control`](https://github.com/MasterSoft24/CloudCross/blob/master/package/debian.control) reads:
```
Depends: libqt5network5, qtbase5, qt5-qmake, libcurl4-openssl
```
This is confusing. I believe that the package was really build against `libcurl4-openssl` even though it does not exist in Debian repo.

**Comment by MasterSoft24** [comment]
I have installed a Debian 9.8 and I can say that you are right. I have changed a debian.control  and rebuild packages. Could you try to install the package again?

**Comment by dmak** [comment]
I have downloaded latest package and it still does not work.
```
# wget -nv 'https://download.opensuse.org/repositories/home:/MasterSoft24/Debian_9.0/i386/cloudcross_1.4.5-2_i386.deb'
# dpkg -i cloudcross_1.4.5-2_i386.deb 
Preparing to unpack .../cloudcross_1.4.5-2_i386.deb ...
Unpacking cloudcross (1.4.5-2) over (1.4.5-1) ...
# strings /usr/bin/ccross | grep CURL_OPENSSL_3
CURL_OPENSSL_3
```
I suppose that `CURL_OPENSSL_3` should not be in the binary. Where can I download `.dsc` file and `.debian.tar.xz` (Debian package sources), so that I can build the package myself (generated by `dpkg-buildpackage -S ...`)?

**Comment by MasterSoft24** [comment]
All files of my build farm  you can find on https://build.opensuse.org/package/show/home:MasterSoft24/cloudcross
For my shame, I 'm a noob in a Debian packaging. I've been would very grateful  If you can fix this.

**Comment by dmak** [comment]
If you look at the [logfile](https://build.opensuse.org/build/home:MasterSoft24/Debian_9.0/x86_64/cloudcross/_log) you can see the following:
```
[  103s] [257/313] installing libcurl3-7.52.1-5+deb9u9
...
[  104s] [259/313] installing libcurl4-openssl-dev-7.52.1-5+deb9u9
```
`libcurl4-openssl-dev` package is correct, but it should depend on `libcurl4` to be compatible with Debian Buster.
After looking around I understood what is the problem. In Debian 9 / Stretch [`libcurl4-openssl-dev` indeed depends on `libcurl3` ](https://packages.debian.org/stretch/libcurl4-openssl-dev) and that is not compatible with Debian 10 / Buster [where it depends on `libcurl4`](https://packages.debian.org/buster/libcurl4-openssl-dev). You need to configure somewhere the additional build target for Debian 10.

Also you have specified that `cloudcross` package depends on `qt5-qmake` in `debian.control`:
```
Depends: libqt5network5, qt5-default, qt5-qmake
```
Is it really so? `qmake` is build utility, so should not be a dependency for the target artifact. Same problems with `qt5-default` which depends on `qt5-qmake`.

I suggest to simply say
```
Depends: ${shlibs:Depends}, ${misc:Depends}
```
the way how [Debian Maintainers' Guide §4.1](https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#control) suggests.

I must admit I should have used [Ubuntu 18 binaries](https://build.opensuse.org/package/binaries/home:MasterSoft24/cloudcross/xUbuntu_18.10) from the very beginning as they work smoothly on Debian 10 / Buster. I have only changed the control file to read
```
Depends: libqt5network5
```

**Comment by MasterSoft24** [comment]
So, I've made changes into debian.control like you suggest. Also, I've added a package for Debian 10. Look it, maybe the trouble is gone.

**Comment by dmak** [comment]
Now I can see that dependencies look very nice:
```
Depends: libc6 (>= 2.14), libcurl4 (>= 7.16.2), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.11.0~rc1), libqt5network5 (>= 5.0.2), libstdc++6 (>= 5.2)                                                                                                                                        
```
I can run `ccross` on Debian Buster. Cool! I am closing the issue. The only slippery place is package [`cloudcross-dbgsym_1.4.5-3_amd64.deb`](https://download.opensuse.org/repositories/home:/MasterSoft24/Debian_10/amd64/cloudcross-dbgsym_1.4.5-3_amd64.deb) which I believe should not show "no debugging symbols found" warning message:
```
# dpkg -i cloudcross-dbgsym_1.4.5-3_amd64.deb                                                    
# dpkg -L cloudcross-dbgsym                                                                      
/usr/lib/debug                                                                                                                    
/usr/lib/debug/.build-id                                   
/usr/lib/debug/.build-id/49                                
/usr/lib/debug/.build-id/49/a30acaa249dcab25b113736c70f090343f7672.debug
/usr/lib/debug/.build-id/5c                                
/usr/lib/debug/.build-id/5c/0a103a910f5a7488c7ba965a9ea7ade35dae51.debug
$ gdb ccross
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Reading symbols from ccross...Reading symbols from /usr/lib/debug/.build-id/49/a30acaa249dcab25b113736c70f090343f7672.debug...(no debugging symbols found)...done.
(no debugging symbols found)...done.
(gdb) 
```
however I cannot suggest here further – I am not sure what should be in that package/file to make `gdb` happy.
