### ISSUE TITLE
MasterSoft24/xUbuntu_18.04 not signed?

### ISSUE THREAD

**Issue by akwala** [MasterSoft24/CloudCross#74]
After adding the repository key, apt-get update reports the following:

> W: GPG error: http://download.opensuse.org/repositories/home:/MasterSoft24/xUbuntu_18.04  Release: The following signatures were invalid: AACBD1927CDA42C2D23F32371EB8A0F2D5D28A05
> **E: The repository 'http://download.opensuse.org/repositories/home:/MasterSoft24/xUbuntu_18.04  Release' is not signed.**
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by MasterSoft24** [comment]
I found this solution: 
```
wget http://download.opensuse.org/repositories/home:/MasterSoft24/xUbuntu_18.04/Release.key -O -
sudo apt-key add -    
sudo apt update 
```
source is a https://unix.stackexchange.com/questions/449248/keyexpired-on-opensuse-repository

**Comment by akwala** [comment]
> I found this solution:
> 
> ```
> wget http://download.opensuse.org/repositories/home:/MasterSoft24/xUbuntu_18.04/Release.key -O -
> sudo apt-key add -    
> sudo apt update 
> ```
> 
> source is a https://unix.stackexchange.com/questions/449248/keyexpired-on-opensuse-repository

I had already added the repo key following the instructions for xUbuntu 18.04 at https://software.opensuse.org//download.html?project=home%3AMasterSoft24&package=cloudcross.

I did it once more, following the instructions you linked to, just to be sure. `apt-get update` still reports the same error. Note that it is _not_ complaining about an expired key like in the post you linked to. This is what `apt-key list` shows:

> pub   dsa1024 2011-08-18 [SC] [expires: 2021-03-29]
>       AACB D192 7CDA 42C2 D23F  3237 1EB8 A0F2 D5D2 8A05
> uid           [ unknown] home:MasterSoft24 OBS Project <home:MasterSoft24@build.opensuse.org>

I also tried after doing `sudo rm -r /var/lib/apt/lists` and `sudo apt-get clean`, and got the same error.

**Comment by akwala** [comment]
Does the following apply to your repo key (from https://unix.stackexchange.com/a/387054/7931; includes instructions for fix)?

> ...support for keys that state a preference for SHA-1 encryption has been turned off in APT as of Debian 9. (Specifically, it was turned off in APT version 1.4~beta1, and Debian 9 has version 1.4.7.)

**Comment by MasterSoft24** [comment]
So, I have changed the key for OBS and rebuilds packages. Could you try to install it now?

**Comment by akwala** [comment]
> So, I have changed the key for OBS and rebuilds packages. Could you try to install it now?

Yep, was able to install after adding the new key. Thanks!
