### ISSUE TITLE
Двухуровневая ауттетификация google 2019

### ISSUE THREAD

**Issue by AlexandrSpb** [MasterSoft24/CloudCross#75]
Проблема точно такая же, как и в 2017 году - https://github.com/MasterSoft24/CloudCross/issues/21
Проходим по ссылке в браузере с другого ПК, разрешаем все и получаем страницу, что невозможно достучаться. Пробовал указывать внутренний IP машины вместо 127.0.0.1 (сеть класса С), но тот же результат. Как быть? Файл .drive не создается.
Система - CentOS 7, все собрано по инструкции с github сегодня.

**Comment by MasterSoft24** [comment]
Имеете ввиду, что ссылку получаете на одной машине, а в браузере открываете на другой? Если так, то такой сценарий не сработает

**Comment by AlexandrSpb** [comment]
Да, верно. Имею ввиду именно это. Как мне открыть ссылку в консоли? На машине нет иксов).

**Comment by MasterSoft24** [comment]
Я думаю тут только один вариант - запустить ccross на машине с иксами, а потом скопировать файл .grive на целевую машину... Ну или попробовать без иксов через linx (я не пробовал)

**Comment by AlexandrSpb** [comment]
Links не прокатил... Попробую первый вариант.

**Comment by AlexandrSpb** [comment]
Трюк прошел, спасибо!
