### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ianferreira** [MasterSoft24/CloudCross#76]
/.local/lib/python3.6/site-packages/tensorflow/contrib/layers/ops/__pycache__/__init__.cpython-36.pyc New local. Uploading.
Segmentation fault (core dumped)

and

Error when upload /home/ian/.cache/chromium/Default/Cache/070fbdaf17fe8dfe_0 on remote
/.local/share/icons/Blue-Maia/actions/22/go-home.svg New local. Uploading.
double free or corruption (!prev)
Aborted (core dumped)

4.18.0-18-generic #19~18.04.1-Ubuntu SMP Fri Apr 5 10:22:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MasterSoft24** [comment]
Is files uploading anyway despite the error?

**Comment by ianferreira** [comment]
Nope. Some do then crash

**Comment by MasterSoft24** [comment]
Please, see a new version that has been fixed this bug

**Comment by MasterSoft24** [comment]
I think this issue was closed by last release
