### ISSUE TITLE
ccross in console mode

### ISSUE THREAD

**Issue by messireL** [MasterSoft24/CloudCross#77]
Beg your pardon, but I can't understand - can it be used in console mode, having no graphic support?
The quest is - how to allow google-drive request? When the URL appears, I copy it to my browser and press "Allow". But after it I see "127.0.0.1" window coz the URL contains redirect to 127.0.0.1.
What I have to do to use this software?

Please, help it.

Lynx/Links etc. can't open the URL coz they dont have javascript support themselves.

**Comment by MasterSoft24** [comment]
You can make the authentication on a machine with the normal desktop then copy .grive file (for GoogleDrive) to the target machine.

**Comment by Riflerat** [comment]
I don't understand it how to, too...

**Comment by MasterSoft24** [comment]
Just do it on your desktop then copy the .grive file to the target host
.grive file does not associate to the machine and can be used on other computers. You must be careful with these files. These files could grant access to your GoogleDrive for any man.
