### ISSUE TITLE
Corrupted directory structure when Dropbox sync

### ISSUE THREAD

**Issue by amorting** [MasterSoft24/CloudCross#78]
Hello!

When sync to Dropbox i have bad directory structure with directory names in lower case.

For example directory structure 

`Dir/SubDir/file.txt`

synced as

```
Dir/SubDir
subdir/file.txt
```
Command:
ccross --provider dropbox --prefer=remote

Version:
cloudcross-1.4.5-7.1.x86_64.rpm

OS:
Fedora 30

**Comment by MasterSoft24** [comment]
Could not confirm. Try to build from source code
