### ISSUE TITLE
Google Oauth fails verification for app

### ISSUE THREAD

**Issue by OlyAndy** [MasterSoft24/CloudCross#82]
I get the following message when i try to authenticate:

Sign in with Google temporarily disabled for this app

This app has not yet been verified by Google in order to use Google Sign in.

**Comment by MasterSoft24** [comment]
Google tightens the rules of uses their services. I send a request to verify CloudCross but this may take several weeks.

**Comment by grobacz** [comment]
Is there any way the community can help with speeding up the process?

**Comment by MasterSoft24** [comment]
This is a good idea. StackOverflow hasn't helped me.
The problem that I'm doesn't understand what should I do. I received an email with instructions:

> Dear Developer,
> 
> Thank you for submitting an OAuth App Verification request. 
> 
> In order to continue with the verification process, you’ll need to create and provide a link to a YouTube video that shows how you’ll use the data you access using OAuth scopes. Specifically, the demo video should detail, in English:
> 
>     How to log into your project (ensuring that the URL bar with the client ID is clearly visible)
> 
>     How to request an OAuth token (OAuth Consent Screen/Permissions Page)
> 
>     How your project's functionality utilizes the requested scopes:
> 
>         https://www.googleapis.com/auth/drive
> 
>         https://www.googleapis.com/auth/spreadsheets 
> 
>         https://www.googleapis.com/auth/docs 
> 
> Note: You don’t need to be personally visible in the  demo or narrate the video. Demonstrating the process from the keyboard/screen view is sufficient.
> 
> You can send us the video by replying to this email with the link. You can find more information in the OAuth Application Verification FAQ. To ensure your communications are not missed, please respond directly to this thread to continue with the verification process. Note that any new email sent to api-oauth-dev-verification@google.com will not be received by our team.

But a problem in how I will show in a video `How to request an OAuth token (OAuth Consent Screen/Permissions Page)` if I see 

> Sign in with Google temporarily disabled  for this app 

after account selects.

**Comment by grobacz** [comment]
https://support.google.com/cloud/answer/6158849?hl=en

Maybe this app has a custom consent screen set up in configuration (7)?

From the email it seems they ask you for a demo of logging in to a web app - and obviously this isn't one.

Or, it could be that the selected application type should be different (6).

I will try looking through the google console configuration in the evening.

**Comment by grobacz** [comment]
Took a little longer.
As I understand the process from documentation here https://support.google.com/cloud/answer/9110914
before you prompt for OAuth you need to provide information about scope the application requires - why and how it is used. So you would need to tweak CLI output a bit and record it as they requested.
During recording of youtube clip you temporarily could switch the application configuration in Google Developers Console to make it internal (OAuth consent screen config like below) so the verification is not needed and it should just work.

![image](https://user-images.githubusercontent.com/4448337/79643565-d6b41580-81a3-11ea-9217-80f8d470cc5e.png)

**Comment by MasterSoft24** [comment]
This choice is relevant only to create a new application.  In my Developers Console, I see

![image](https://user-images.githubusercontent.com/2410915/80111859-a2c55f80-85aa-11ea-9177-9cb52f38309c.png)

Target button is inactive

**Comment by nsi-test** [comment]
I am not a developer, so what I say may be stupid. But couldn’t you get a 14-day free trial just to pass this step. And moreover you can get a Google nonprofits account as it is described here: https://usefyi.com/g-suite-for-nonprofits/ . Google became bastards of course but this is other thing.

**Comment by MasterSoft24** [comment]
Thanks for a links.  I will try it soon

**Comment by MasterSoft24** [comment]
fixed by the last 1.4.7 release

**Comment by nsi-test** [comment]
Thank you very much, man. Meanwhile I swithched to onedrive, but the more is better.  May be you can mark this issue as "closed". I tried it on  1.4.8.
