### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by quiricada** [MasterSoft24/CloudCross#83]
Linux lenovox 5.4.31 #1 SMP Wed Apr 8 13:51:46 CDT 2020 x86_64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz GenuineIntel GNU/Linux

slackware64-current

make
cd MSHttpRequest/ && make -f Makefile 
make[1]: Entering directory '/home/db/Downloads/CloudCross-master/build/MSHttpRequest'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/lib64/qt/mkspecs/linux-g++ -I../../MSHttpRequest -I/usr/lib64/qt/include/QtCore -I/usr/lib64/qt/include/QtNetwork -I/usr/lib64/qt/include -I. -I../../MSHttpRequest -I. -o main.o ../../MSHttpRequest/main.cpp
../../MSHttpRequest/main.cpp: In function ‘int main(int, char**)’:
../../MSHttpRequest/main.cpp:68:20: error: ‘QStringLiteral’ was not declared in this scope; did you mean ‘QStringList’?
   68 |     req->addHeader(QStringLiteral("My-Testing_header"),QStringLiteral("test_header/content"));
      |                    ^~~~~~~~~~~~~~
      |                    QStringList
make[1]: *** [Makefile:250: main.o] Error 1
make[1]: Leaving directory '/home/db/Downloads/CloudCross-master/build/MSHttpRequest'
make: *** [Makefile:41: sub-MSHttpRequest-MSHttpRequest-pro-make_default] Error 2

**Comment by MasterSoft24** [comment]
What a Qt version you use?

**Comment by MasterSoft24** [comment]
Need more info
