### ISSUE TITLE
Dropbox sync not working

### ISSUE THREAD

**Issue by vnln** [MasterSoft24/CloudCross#85]
```
$ ccross -a --provider dropbox
-------------------------------------
"Please go to this URL and confirm application credentials\n"
"%URL%"
"Token was succesfully accepted and saved. To start working with the program run ccross without any options for start full synchronize."

$ ccross
"Previous state file not found. Start in stateless mode."
"Access key missing or corrupt. Start CloudCross with -a option for obtained private key."
```

Authentification shows no problems, ".dbox" file actually appears in designated folder but still nothing works.

**Comment by MasterSoft24** [comment]
Try 
`ccross -s --provider dropbox`
for example. `ccross` without params is not the correct syntax.

**Comment by vnln** [comment]
Sorry, my bad. It's working fine. I was just following instructions from your web site, it says "OR". That's where i got confused. Thanks, anyway.

![ccross](https://user-images.githubusercontent.com/71157087/97164986-66163300-179c-11eb-9333-1b6963c98f68.jpg)
