### ISSUE TITLE
Files randomly change

### ISSUE THREAD

**Issue by mkauzlar** [MasterSoft24/CloudCross#9]
Hi,
after installing ccross I created a folder and did the following in it:
1. ccross -a (then added the google code)
2. ccross --prefer=remote (wait for sync to finish)
3. ccross --prefer=remote (again to check that all is synched)

After step 3. I get:

/some/random/file    Changed local. Uploading

This happens randomly on some files even though I haven't touched any files.

**Comment by MasterSoft24** [comment]
i can't reproduce this behaviour. Please give me more information.(distro, ccross version, filesystem type and if it possible full log of synchronization).

This behavour possible for Google docs files

**Comment by mkauzlar** [comment]
Linux Mint 18 Sarah (GNU/Linux 4.4.0-21-generic x86_64)
CloudCross v1.2.2 for Linux
ext4
Log (I changed the file names):
$ ccross --prefer=remote  --dry-run
Reading remote files
Reading local files and folders
Checking folder structure on local
Start syncronization
/Papiri/Diplome/file1.pdf Changed local. Uploading.
/Letenje/Logbook/file2 New remote. Downloading.
/Posao/ulazni_Racuni/2015/file3.pdf Changed local. Uploading.
/Letenje/file4.zsheet New remote. Downloading.
/Papiri/file5.pdf Changed local. Uploading.
/file6.csv Changed local. Uploading.
/Letenje/Logbook/file8 [Form] New remote. Downloading.

Nothing really changed on the local file system or on google drive. Some files repeat every time I run the command while others appear or disappear randomly

**Comment by MasterSoft24** [comment]
Do you compile ccross from source code or install deb package? And next question- what do you have Qt version?

**Comment by mkauzlar** [comment]
I installed the deb version. I think both qt4 and qt5 libraries are installed.

**Comment by MasterSoft24** [comment]
i mean qt5 version i.e. 5.2 or 5.6

**Comment by mkauzlar** [comment]
$ qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

**Comment by MasterSoft24** [comment]
i'm will be try reproduce this bug. About result i 'll be write later

**Comment by MasterSoft24** [comment]
Unfortunately i'm can't reproduce bug in fresh installed Linux Mint Sarah Mate. I was trying install cloudcross-1.2.2-2_amd64.deb package  from site cloudcross.mastersoft24.ru and described you behaviour not reproduced.

If you can you might compile ccross from source code.  If bug is disappear then it trait of Linux Mint and his Qt compilation

**Comment by mkauzlar** [comment]
Ok, I'm on vacation now. Will try it when I'm back in 10 days

**Comment by mkauzlar** [comment]
Ok, I'm back.
I have a new laptop now. I installed Mint Sarah Cinnemon. And the behavior is the same:
1. Install Mint
2. Download and install deb package of ccross
3. Create empty directory and cd into it
4. ccross -a (then added the google code)
5. ccross --prefer=remote (wait for sync to finish)
6. Run ccross n amount of times and get random changed files to upload (some files appear more often than others though)

I will now install stock Ubuntu 14.04 and try to do the same

**Comment by MasterSoft24** [comment]
Ok. Which file extensions have the changed files? Do you share this files or not?
I still can't reproduce.

**Comment by mkauzlar** [comment]
some are pdf, some are xml, some are something else, some are shared and some not, I can't see any pattern.

for instance the file:
 $ file "Stanovi/Stan Pecine/Saipem-Obrazac-0209.pdf"
Stanovi/Stan Pecine/Saipem-Obrazac-0209.pdf: PDF document, version 1.4

which is really an old file which I didn't change ever from 2009:

$ ls -l "Stanovi/Stan Pecine/Saipem-Obrazac-0209.pdf"
-rw------- 1 mkauzlar mkauzlar 52782 Tra  1  2009 Stanovi/Stan Pecine/Saipem-Obrazac-0209.pdf

yet ccross says:
/Stanovi/Stan Pecine/Saipem-Obrazac-0209.pdf New local. Uploading. (sometimes it says Changed local. Uploading).

If I do the same procedure with grive I have no errors and sync works correctly

**Comment by MasterSoft24** [comment]
This file (Saipem-Obrazac-0209.pdf) uploaded/downloaded every time or sometimes it may be ignored?

grive as i know use different way to define changes in files.

**Comment by mkauzlar** [comment]
I'm now running with --dry-run as I don't want things to change on my google drive so with --dry-run it says it every time now. Sorry I don't feel like risking changing or deleting stuff by running tests.
Anyhow on the local file system the file is 52782kb from April 1st 2009, the same is on google drive so it should not say that is a new file which needs to be uploaded.
Moreover if I download the file manually from google drive and do a diff with the one on the file system there are no differences. 
So the files are identical with the same timestamp.

**Comment by MasterSoft24** [comment]
If you can, try upload this file to root of Google drive with different name with any english locale. And try sync (dry-run). If it to be continued I have no idea why this behaviour happend. As i said i can't reproduce it.
